# Generated by Django 5.1.6 on 2025-04-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.TextField(default='Enginering dinner'),
            preserve_default=False,
        ),
    ]
