# Generated by Django 5.1.6 on 2025-04-01 22:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
