# Generated by Django 5.1.6 on 2025-02-20 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='category',
            new_name='programe',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
