# Generated by Django 5.1.6 on 2025-02-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='swipes',
            field=models.BigIntegerField(default=0),
        ),
    ]
