# Generated by Django 5.1.6 on 2025-03-25 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_customuser_swipes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimage',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='more_images',
        ),
        migrations.AddField(
            model_name='userimage',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userimage',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
