# Generated by Django 5.1.6 on 2025-03-25 20:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_userimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='matches',
            field=models.ManyToManyField(related_name='matches_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
