# Generated by Django 5.1.6 on 2025-05-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_customuser_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='school',
            field=models.CharField(blank=True, choices=[('Skandinaviens akademi för psykoterapiutveckling', 'Skandinaviens akademi för psykoterapiutveckling'), ('Svenska institutet för kognitiv psykoterapi', 'Svenska institutet för kognitiv psykoterapi'), ('Röda Korsets Högskola', 'Röda Korsets Högskola'), ('Brunnsviks folkhögskola', 'Brunnsviks folkhögskola'), ('Uppsala Universitet', 'Uppsala Universitet'), ('Örebro universitet', 'Örebro universitet'), ('Kungliga Musikhögskolan', 'Kungliga Musikhögskolan'), ('Malmö universitet', 'Malmö universitet'), ('Världssjöfartsuniversitetet', 'Världssjöfartsuniversitetet'), ('Sophiahemmet Högskola', 'Sophiahemmet Högskola'), ('Gymnastik- och idrottshögskolans', 'Gymnastik- och idrottshögskolans'), ('Chalmers Lunds universitet', 'Chalmers Lunds universitet'), ('Stockholm universitet', 'Stockholm universitet'), ('Umeå Universitet', 'Umeå Universitet'), ('Kungliga Tekniska Högskolan', 'Kungliga Tekniska Högskolan'), ('Luleå tekniska universitet', 'Luleå tekniska universitet'), ('Högskolan i Borås', 'Högskolan i Borås'), ('Akademi för ledarskap och teologi', 'Akademi för ledarskap och teologi'), ('Stockholms Musikpedagogiska Institut', 'Stockholms Musikpedagogiska Institut'), ('Blekinge Tekniska Högskola', 'Blekinge Tekniska Högskola'), ('Försvarshögskolan', 'Försvarshögskolan'), ('Högskolan Väst', 'Högskolan Väst'), ('Högskolan i Halmstad', 'Högskolan i Halmstad'), ('Mittuniversitetet', 'Mittuniversitetet'), ('Linköpings Universitet', 'Linköpings Universitet'), ('Newmaninstitutet', 'Newmaninstitutet'), ('Konstfack', 'Konstfack'), ('Beckmans designhögskola', 'Beckmans designhögskola'), ('Högskolan i Skövde', 'Högskolan i Skövde'), ('Göteborg universitet', 'Göteborg universitet'), ('Stiftelsen Högskolan i Jönköping', 'Stiftelsen Högskolan i Jönköping'), ('Karolinska Institutet', 'Karolinska Institutet'), ('Högskolan Dalarna', 'Högskolan Dalarna'), ('Handels', 'Handels'), ('Kungliga Konsthögskolan', 'Kungliga Konsthögskolan'), ('Johannelunds teologiska högskola', 'Johannelunds teologiska högskola'), ('Gammelkroppa skogsskola', 'Gammelkroppa skogsskola'), ('Stockholms konstnärliga högskola', 'Stockholms konstnärliga högskola'), ('Högskolan Kristianstad', 'Högskolan Kristianstad'), ('Sveriges lantbruksuniversitet', 'Sveriges lantbruksuniversitet'), ('Mälardalens universitet', 'Mälardalens universitet'), ('Ericastiftelsen', 'Ericastiftelsen'), ('Karlstads universitet', 'Karlstads universitet'), ('Linnéuniversitetet', 'Linnéuniversitetet'), ('Högskolan i Gävle', 'Högskolan i Gävle'), ('Södertörns högskola', 'Södertörns högskola'), ('Marie Cederschiöld högskola', 'Marie Cederschiöld högskola'), ('Enskilda Högskolan Stockholm', 'Enskilda Högskolan Stockholm')], max_length=255),
        ),
    ]
